name: Deploy TfL Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://template.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name tfl-reliability-platform-dev \
            --parameter-overrides \
              EnvironmentName=dev \
              AlertEmail="${{ secrets.ALERT_EMAIL }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --region eu-west-2